version: '3.4'
services:
  twitter-slack-bot:
    build: bot_files
    image: covid19ab_twitter_slack_bot/bot_files:latest
    ports:
      - "5500:5500"
    environment: 
      - BEARER_TOKEN_TWITTER
      - BEARER_TOKEN_SLACK
      - SLACK_CHANNEL_NAME
      - SLACK_CHANNEL_ID